In [1]:
import numpy as np
from boxmot.utils.iou import AssociationFunction
from storage import TrackStorage

#autoreload
%load_ext autoreload
%autoreload 2

In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

In [11]:
index_tuple = (0, 1)

# Indexing the array using the tuple
value = arr[:, index_tuple]

print(value)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]

 [[19 20 21]
  [22 23 24]]]


In [15]:
a = np.array([[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]])
b = np.array([[2, 1, 9, 10], [2, 4, 11, 12], [11, 12, 13, 14]])

c = AssociationFunction.iou_batch(a, b)

In [16]:
storage = TrackStorage(50)

In [17]:
for i in range(3):
    storage.means[i] = 5

In [24]:
storage.means != 4

array([0, 1, 2])

In [ ]:
storage.dets.shape

KeyError: 'dets'

In [12]:
storage.means[[0, 1, 2]] = [1, 2, 3]

(50,) [0, 1, 2] [1, 2, 3]


In [13]:
storage.means

array([1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [ ]:
storage.dets[[0, 1, 2]] = [2, 3, 4, 5]

(50, 4) [0, 1, 2] [2, 3, 4, 5]


In [ ]:
storage.dets

array([[2, 3, 4, 5],
       [2, 3, 4, 5],
       [2, 3, 4, 5],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0,

In [ ]:
storage.dets[[0, 1, 2]] = b

(50, 4) [0, 1, 2] [[ 2  1  9 10]
 [ 2  4 11 12]
 [11 12 13 14]]


In [ ]:
storage.dets

array([[ 2,  1,  9, 10],
       [ 2,  4, 11, 12],
       [11, 12, 13, 14],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],


In [36]:
a = np.zeros((15, 4))

In [38]:
a[[1, 2, 3]] = b

In [39]:
a

array([[ 0.,  0.,  0.,  0.],
       [ 2.,  1.,  9., 10.],
       [ 2.,  4., 11., 12.],
       [11., 12., 13., 14.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
c

array([[0.03076923, 0.        , 0.        ],
       [0.06349206, 0.05555556, 0.        ],
       [0.06349206, 0.05555556, 0.        ]])

In [ ]:
p, q = np.where(c < 0.05)



array([0, 0, 0, 1, 2])

In [3]:
t_xyxy = np.array([[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]])
t_ids = np.array([1, 2, 3])
t_confs = np.array([0.1, 0.2, 0.3])

In [8]:
dets_high_pool = np.arange(15)
dets_low_pool = np.arange(15, 19)

dets_low_pool

array([15, 16, 17, 18])

In [7]:
a = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
b = {3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

a - b

{1, 2}

In [11]:
t_xyxy[[a - b]]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [12]:
import pickle

In [22]:
arra

array([[1.00000e+00, 9.00000e+02, 5.85000e+02, ..., 1.00000e+00,
        0.00000e+00, 9.54937e-01],
       [1.00000e+00, 9.01000e+02, 1.34100e+03, ..., 1.00000e+00,
        0.00000e+00, 9.36358e-01],
       [1.00000e+00, 9.02000e+02, 6.31000e+02, ..., 1.00000e+00,
        0.00000e+00, 9.34299e-01],
       ...,
       [6.00000e+02, 1.02700e+03, 1.04300e+03, ..., 1.00000e+00,
        0.00000e+00, 6.33705e-01],
       [6.00000e+02, 1.08600e+03, 5.77000e+02, ..., 1.00000e+00,
        0.00000e+00, 6.56878e-01],
       [6.00000e+02, 1.07300e+03, 1.06300e+03, ..., 1.00000e+00,
        0.00000e+00, 6.72830e-01]])

In [ ]:
arra[arra[:, 0] == 1][:, [0, 2, 3, 4, 5, 6, 7, 8]]

array([[1.00000e+00, 5.85000e+02, 4.46000e+02, 8.50000e+01, 2.61000e+02,
        1.00000e+00, 0.00000e+00, 9.54937e-01],
       [1.00000e+00, 1.34100e+03, 4.18000e+02, 1.60000e+02, 3.66000e+02,
        1.00000e+00, 0.00000e+00, 9.36358e-01],
       [1.00000e+00, 6.31000e+02, 4.58000e+02, 6.60000e+01, 1.86000e+02,
        1.00000e+00, 0.00000e+00, 9.34299e-01],
       [1.00000e+00, 1.08900e+03, 4.83000e+02, 3.20000e+01, 1.14000e+02,
        1.00000e+00, 0.00000e+00, 9.17573e-01],
       [1.00000e+00, 4.40000e+02, 4.46000e+02, 1.09000e+02, 2.76000e+02,
        1.00000e+00, 0.00000e+00, 9.16055e-01],
       [1.00000e+00, 1.05500e+03, 4.83000e+02, 3.60000e+01, 1.11000e+02,
        1.00000e+00, 0.00000e+00, 9.13944e-01],
       [1.00000e+00, 5.47000e+02, 4.60000e+02, 3.40000e+01, 9.80000e+01,
        1.00000e+00, 0.00000e+00, 9.08725e-01],
       [1.00000e+00, 1.42100e+03, 4.27000e+02, 1.82000e+02, 3.34000e+02,
        1.00000e+00, 0.00000e+00, 8.84765e-01],
       [1.00000e+00, 1.09800e+03

In [90]:
def check_trackers(file_a, file_b):
    arra = np.loadtxt(file_a, delimiter=",")
    arrb = np.loadtxt(file_b, delimiter=",")

    frames_cnt = int(np.max(arra[:, 0]))

    for i in range(frames_cnt):
        arra_check = arra[arra[:, 0] == i]
        arrb_check = arrb[arrb[:, 0] == i]

        arra_check = arra_check[arra_check[:, 1].argsort()][:, [0, 2, 3, 4, 5, 6, 7, 8]]
        arrb_check = arrb_check[arrb_check[:, 1].argsort()][:, [0, 2, 3, 4, 5, 6, 7, 8]]

        if np.array_equal(arra_check, arrb_check):
            pass
        else:
            print(f"Not equal: {i}")
            print(arra_check.shape, arrb_check.shape)

            for j in range(arra_check.shape[0]):
                if not np.array_equal(arra_check[j], arrb_check[j]):
                    print(arra_check[j])
                    print(arrb_check[j])
            raise ValueError
    
    return True


In [91]:
file_a = "/home/kozakmv/Programming/Python/boxmot/runs/mot/yolox_m_osnet_x1_0_msmt17_puretrack_new/MOT17-11.txt"
file_b = "/home/kozakmv/Programming/Python/boxmot/runs/mot/yolox_m_osnet_x1_0_msmt17_puretrack/MOT17-11.txt"

In [92]:
check_trackers(file_a, file_b)

Not equal: 48
(13, 8) (14, 8)
[4.80000e+01 1.11000e+03 3.87000e+02 1.54000e+02 4.45000e+02 1.00000e+00
 0.00000e+00 9.38678e-01]
[4.8000e+01 9.1400e+02 4.7300e+02 4.4000e+01 1.2000e+02 1.0000e+00
 0.0000e+00 6.8909e-01]
[4.80000e+01 8.83000e+02 4.76000e+02 3.80000e+01 1.15000e+02 1.00000e+00
 0.00000e+00 8.56832e-01]
[4.80000e+01 1.11000e+03 3.87000e+02 1.54000e+02 4.45000e+02 1.00000e+00
 0.00000e+00 9.38678e-01]
[ 48.       832.       462.        56.       154.         1.
   0.         0.900179]
[4.80000e+01 8.83000e+02 4.76000e+02 3.80000e+01 1.15000e+02 1.00000e+00
 0.00000e+00 8.56832e-01]
[4.80000e+01 1.54400e+03 4.59000e+02 4.30000e+01 1.27000e+02 1.00000e+00
 0.00000e+00 8.87442e-01]
[ 48.       832.       462.        56.       154.         1.
   0.         0.900179]
[ 48.       782.       479.        48.       136.         1.
   0.         0.895409]
[4.80000e+01 1.54400e+03 4.59000e+02 4.30000e+01 1.27000e+02 1.00000e+00
 0.00000e+00 8.87442e-01]
[4.80000e+01 1.40400e+03 4.810

ValueError: 