In [3]:
import numpy as np
from boxmot.utils.iou import AssociationFunction
from storage import TrackStorage
from utils import xyxy2xywh, xywh2xyxy

#autoreload
%load_ext autoreload
%autoreload 2

In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

In [11]:
index_tuple = (0, 1)

# Indexing the array using the tuple
value = arr[:, index_tuple]

print(value)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]

 [[19 20 21]
  [22 23 24]]]


In [15]:
a = np.array([[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]])
b = np.array([[2, 1, 9, 10], [2, 4, 11, 12], [11, 12, 13, 14]])

c = AssociationFunction.iou_batch(a, b)

In [16]:
storage = TrackStorage(50)

In [17]:
for i in range(3):
    storage.means[i] = 5

In [24]:
storage.means != 4

array([0, 1, 2])

In [ ]:
storage.boxes.shape

KeyError: 'dets'

In [12]:
storage.means[[0, 1, 2]] = [1, 2, 3]

(50,) [0, 1, 2] [1, 2, 3]


In [13]:
storage.means

array([1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [ ]:
storage.boxes[[0, 1, 2]] = [2, 3, 4, 5]

(50, 4) [0, 1, 2] [2, 3, 4, 5]


In [ ]:
storage.boxes

array([[2, 3, 4, 5],
       [2, 3, 4, 5],
       [2, 3, 4, 5],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0,

In [ ]:
storage.boxes[[0, 1, 2]] = b

(50, 4) [0, 1, 2] [[ 2  1  9 10]
 [ 2  4 11 12]
 [11 12 13 14]]


In [ ]:
storage.boxes

array([[ 2,  1,  9, 10],
       [ 2,  4, 11, 12],
       [11, 12, 13, 14],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],


In [36]:
a = np.zeros((15, 4))

In [38]:
a[[1, 2, 3]] = b

In [39]:
a

array([[ 0.,  0.,  0.,  0.],
       [ 2.,  1.,  9., 10.],
       [ 2.,  4., 11., 12.],
       [11., 12., 13., 14.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
c

array([[0.03076923, 0.        , 0.        ],
       [0.06349206, 0.05555556, 0.        ],
       [0.06349206, 0.05555556, 0.        ]])

In [ ]:
p, q = np.where(c < 0.05)



array([0, 0, 0, 1, 2])

In [3]:
t_xyxy = np.array([[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]])
t_ids = np.array([1, 2, 3])
t_confs = np.array([0.1, 0.2, 0.3])

In [8]:
dets_high_pool = np.arange(15)
dets_low_pool = np.arange(15, 19)

dets_low_pool

array([15, 16, 17, 18])

In [7]:
a = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
b = {3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

a - b

{1, 2}

In [11]:
t_xyxy[[a - b]]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [12]:
import pickle

In [22]:
arra

array([[1.00000e+00, 9.00000e+02, 5.85000e+02, ..., 1.00000e+00,
        0.00000e+00, 9.54937e-01],
       [1.00000e+00, 9.01000e+02, 1.34100e+03, ..., 1.00000e+00,
        0.00000e+00, 9.36358e-01],
       [1.00000e+00, 9.02000e+02, 6.31000e+02, ..., 1.00000e+00,
        0.00000e+00, 9.34299e-01],
       ...,
       [6.00000e+02, 1.02700e+03, 1.04300e+03, ..., 1.00000e+00,
        0.00000e+00, 6.33705e-01],
       [6.00000e+02, 1.08600e+03, 5.77000e+02, ..., 1.00000e+00,
        0.00000e+00, 6.56878e-01],
       [6.00000e+02, 1.07300e+03, 1.06300e+03, ..., 1.00000e+00,
        0.00000e+00, 6.72830e-01]])

In [ ]:
arra[arra[:, 0] == 1][:, [0, 2, 3, 4, 5, 6, 7, 8]]

array([[1.00000e+00, 5.85000e+02, 4.46000e+02, 8.50000e+01, 2.61000e+02,
        1.00000e+00, 0.00000e+00, 9.54937e-01],
       [1.00000e+00, 1.34100e+03, 4.18000e+02, 1.60000e+02, 3.66000e+02,
        1.00000e+00, 0.00000e+00, 9.36358e-01],
       [1.00000e+00, 6.31000e+02, 4.58000e+02, 6.60000e+01, 1.86000e+02,
        1.00000e+00, 0.00000e+00, 9.34299e-01],
       [1.00000e+00, 1.08900e+03, 4.83000e+02, 3.20000e+01, 1.14000e+02,
        1.00000e+00, 0.00000e+00, 9.17573e-01],
       [1.00000e+00, 4.40000e+02, 4.46000e+02, 1.09000e+02, 2.76000e+02,
        1.00000e+00, 0.00000e+00, 9.16055e-01],
       [1.00000e+00, 1.05500e+03, 4.83000e+02, 3.60000e+01, 1.11000e+02,
        1.00000e+00, 0.00000e+00, 9.13944e-01],
       [1.00000e+00, 5.47000e+02, 4.60000e+02, 3.40000e+01, 9.80000e+01,
        1.00000e+00, 0.00000e+00, 9.08725e-01],
       [1.00000e+00, 1.42100e+03, 4.27000e+02, 1.82000e+02, 3.34000e+02,
        1.00000e+00, 0.00000e+00, 8.84765e-01],
       [1.00000e+00, 1.09800e+03

In [90]:
def check_trackers(file_a, file_b):
    arra = np.loadtxt(file_a, delimiter=",")
    arrb = np.loadtxt(file_b, delimiter=",")

    frames_cnt = int(np.max(arra[:, 0]))

    for i in range(frames_cnt):
        arra_check = arra[arra[:, 0] == i]
        arrb_check = arrb[arrb[:, 0] == i]

        arra_check = arra_check[arra_check[:, 1].argsort()][:, [0, 2, 3, 4, 5, 6, 7, 8]]
        arrb_check = arrb_check[arrb_check[:, 1].argsort()][:, [0, 2, 3, 4, 5, 6, 7, 8]]

        if np.array_equal(arra_check, arrb_check):
            pass
        else:
            print(f"Not equal: {i}")
            print(arra_check.shape, arrb_check.shape)

            for j in range(arra_check.shape[0]):
                if not np.array_equal(arra_check[j], arrb_check[j]):
                    print(arra_check[j])
                    print(arrb_check[j])
            raise ValueError
    
    return True


In [91]:
file_a = "/home/kozakmv/Programming/Python/boxmot/runs/mot/yolox_m_osnet_x1_0_msmt17_puretrack_new/MOT17-11.txt"
file_b = "/home/kozakmv/Programming/Python/boxmot/runs/mot/yolox_m_osnet_x1_0_msmt17_puretrack/MOT17-11.txt"

In [92]:
check_trackers(file_a, file_b)

Not equal: 48
(13, 8) (14, 8)
[4.80000e+01 1.11000e+03 3.87000e+02 1.54000e+02 4.45000e+02 1.00000e+00
 0.00000e+00 9.38678e-01]
[4.8000e+01 9.1400e+02 4.7300e+02 4.4000e+01 1.2000e+02 1.0000e+00
 0.0000e+00 6.8909e-01]
[4.80000e+01 8.83000e+02 4.76000e+02 3.80000e+01 1.15000e+02 1.00000e+00
 0.00000e+00 8.56832e-01]
[4.80000e+01 1.11000e+03 3.87000e+02 1.54000e+02 4.45000e+02 1.00000e+00
 0.00000e+00 9.38678e-01]
[ 48.       832.       462.        56.       154.         1.
   0.         0.900179]
[4.80000e+01 8.83000e+02 4.76000e+02 3.80000e+01 1.15000e+02 1.00000e+00
 0.00000e+00 8.56832e-01]
[4.80000e+01 1.54400e+03 4.59000e+02 4.30000e+01 1.27000e+02 1.00000e+00
 0.00000e+00 8.87442e-01]
[ 48.       832.       462.        56.       154.         1.
   0.         0.900179]
[ 48.       782.       479.        48.       136.         1.
   0.         0.895409]
[4.80000e+01 1.54400e+03 4.59000e+02 4.30000e+01 1.27000e+02 1.00000e+00
 0.00000e+00 8.87442e-01]
[4.80000e+01 1.40400e+03 4.810

ValueError: 

In [4]:
def iou_batch(bboxes1, bboxes2) -> np.ndarray:
    bboxes2 = np.expand_dims(bboxes2, 0)
    bboxes1 = np.expand_dims(bboxes1, 1)

    xx1 = np.maximum(bboxes1[..., 0], bboxes2[..., 0])
    yy1 = np.maximum(bboxes1[..., 1], bboxes2[..., 1])
    xx2 = np.minimum(bboxes1[..., 2], bboxes2[..., 2])
    yy2 = np.minimum(bboxes1[..., 3], bboxes2[..., 3])
    w = np.maximum(0.0, xx2 - xx1)
    h = np.maximum(0.0, yy2 - yy1)
    wh = w * h
    o = wh / (
        (bboxes1[..., 2] - bboxes1[..., 0]) * (bboxes1[..., 3] - bboxes1[..., 1]) +
        (bboxes2[..., 2] - bboxes2[..., 0]) * (bboxes2[..., 3] - bboxes2[..., 1]) -
        wh
    )
    return o

In [5]:

def iou_batch_xywh(bboxes1, bboxes2) -> np.ndarray:
    bboxes2 = np.expand_dims(bboxes2, 0)
    bboxes1 = np.expand_dims(bboxes1, 1)

    # Calculate the coordinates of the top-left and bottom-right corners
    bboxes1_x1 = bboxes1[..., 0] - bboxes1[..., 2] / 2
    bboxes1_y1 = bboxes1[..., 1] - bboxes1[..., 3] / 2
    bboxes1_x2 = bboxes1[..., 0] + bboxes1[..., 2] / 2
    bboxes1_y2 = bboxes1[..., 1] + bboxes1[..., 3] / 2

    bboxes2_x1 = bboxes2[..., 0] - bboxes2[..., 2] / 2
    bboxes2_y1 = bboxes2[..., 1] - bboxes2[..., 3] / 2
    bboxes2_x2 = bboxes2[..., 0] + bboxes2[..., 2] / 2
    bboxes2_y2 = bboxes2[..., 1] + bboxes2[..., 3] / 2

    # Determine the coordinates of the intersection rectangle
    xx1 = np.maximum(bboxes1_x1, bboxes2_x1)
    yy1 = np.maximum(bboxes1_y1, bboxes2_y1)
    xx2 = np.minimum(bboxes1_x2, bboxes2_x2)
    yy2 = np.minimum(bboxes1_y2, bboxes2_y2)

    # Compute the width and height of the intersection rectangle
    w = np.maximum(0.0, xx2 - xx1)
    h = np.maximum(0.0, yy2 - yy1)

    # Compute the area of the intersection rectangle
    inter_area = w * h

    # Compute the area of both the prediction and ground-truth rectangles
    bboxes1_area = bboxes1[..., 2] * bboxes1[..., 3]
    bboxes2_area = bboxes2[..., 2] * bboxes2[..., 3]

    # Compute the intersection over union by taking the intersection
    # area and dividing it by the sum of prediction + ground-truth
    # areas minus the intersection area
    o = inter_area / (bboxes1_area + bboxes2_area - inter_area)

    return o

In [10]:
def iou_batch_xywh_faster(bboxes1, bboxes2) -> np.ndarray:
    bboxes2 = np.expand_dims(bboxes2, 0)
    bboxes1 = np.expand_dims(bboxes1, 1)

    # Calculate half widths and half heights
    half_w1 = bboxes1[..., 2] / 2
    half_h1 = bboxes1[..., 3] / 2
    half_w2 = bboxes2[..., 2] / 2
    half_h2 = bboxes2[..., 3] / 2

    # Calculate the coordinates of the top-left and bottom-right corners
    bboxes1_x1 = bboxes1[..., 0] - half_w1
    bboxes1_y1 = bboxes1[..., 1] - half_h1
    bboxes1_x2 = bboxes1[..., 0] + half_w1
    bboxes1_y2 = bboxes1[..., 1] + half_h1

    bboxes2_x1 = bboxes2[..., 0] - half_w2
    bboxes2_y1 = bboxes2[..., 1] - half_h2
    bboxes2_x2 = bboxes2[..., 0] + half_w2
    bboxes2_y2 = bboxes2[..., 1] + half_h2

    # Determine the coordinates of the intersection rectangle
    xx1 = np.maximum(bboxes1_x1, bboxes2_x1)
    yy1 = np.maximum(bboxes1_y1, bboxes2_y1)
    xx2 = np.minimum(bboxes1_x2, bboxes2_x2)
    yy2 = np.minimum(bboxes1_y2, bboxes2_y2)

    # Compute the width and height of the intersection rectangle
    inter_w = np.maximum(0.0, xx2 - xx1)
    inter_h = np.maximum(0.0, yy2 - yy1)

    # Compute the area of the intersection rectangle
    inter_area = inter_w * inter_h

    # Compute the area of both the prediction and ground-truth rectangles
    bboxes1_area = bboxes1[..., 2] * bboxes1[..., 3]
    bboxes2_area = bboxes2[..., 2] * bboxes2[..., 3]

    # Compute the intersection over union
    union_area = bboxes1_area + bboxes2_area - inter_area
    iou = inter_area / union_area

    return iou

In [18]:
def iou_batch_xywh_fastest(bboxes1, bboxes2) -> np.ndarray:
    bboxes2 = np.expand_dims(bboxes2, 0)
    bboxes1 = np.expand_dims(bboxes1, 1)

    # Calculate half widths and half heights
    half_w1, half_h1 = bboxes1[..., 2] / 2, bboxes1[..., 3] / 2
    half_w2, half_h2 = bboxes2[..., 2] / 2, bboxes2[..., 3] / 2

    # Calculate the coordinates of the top-left and bottom-right corners
    bboxes1_x1, bboxes1_y1 = bboxes1[..., 0] - half_w1, bboxes1[..., 1] - half_h1
    bboxes1_x2, bboxes1_y2 = bboxes1[..., 0] + half_w1, bboxes1[..., 1] + half_h1

    bboxes2_x1, bboxes2_y1 = bboxes2[..., 0] - half_w2, bboxes2[..., 1] - half_h2
    bboxes2_x2, bboxes2_y2 = bboxes2[..., 0] + half_w2, bboxes2[..., 1] + half_h2

    # Determine the coordinates of the intersection rectangle
    xx1 = np.maximum(bboxes1_x1, bboxes2_x1)
    yy1 = np.maximum(bboxes1_y1, bboxes2_y1)
    xx2 = np.minimum(bboxes1_x2, bboxes2_x2)
    yy2 = np.minimum(bboxes1_y2, bboxes2_y2)

    # Compute the width and height of the intersection rectangle
    inter_w = np.maximum(0.0, xx2 - xx1)
    inter_h = np.maximum(0.0, yy2 - yy1)

    # Compute the area of the intersection rectangle
    inter_area = inter_w * inter_h

    # Compute the area of both the prediction and ground-truth rectangles
    bboxes1_area = bboxes1[..., 2] * bboxes1[..., 3]
    bboxes2_area = bboxes2[..., 2] * bboxes2[..., 3]

    # Compute the intersection over union
    union_area = bboxes1_area + bboxes2_area - inter_area
    iou = inter_area / union_area

    return iou

In [ ]:
def iou_batch_xywh_fastest(bboxes1, bboxes2) -> np.ndarray:
    bboxes2 = np.expand_dims(bboxes2, 0)
    bboxes1 = np.expand_dims(bboxes1, 1)

    # Calculate half widths and half heights
    half_w1, half_h1 = bboxes1[..., 2] / 2, bboxes1[..., 3] / 2
    half_w2, half_h2 = bboxes2[..., 2] / 2, bboxes2[..., 3] / 2

    # Calculate the coordinates of the top-left and bottom-right corners
    bboxes1_x1, bboxes1_y1 = bboxes1[..., 0] - half_w1, bboxes1[..., 1] - half_h1
    bboxes1_x2, bboxes1_y2 = bboxes1[..., 0] + half_w1, bboxes1[..., 1] + half_h1

    bboxes2_x1, bboxes2_y1 = bboxes2[..., 0] - half_w2, bboxes2[..., 1] - half_h2
    bboxes2_x2, bboxes2_y2 = bboxes2[..., 0] + half_w2, bboxes2[..., 1] + half_h2

    # Determine the coordinates of the intersection rectangle
    xx1 = np.maximum(bboxes1_x1, bboxes2_x1)
    yy1 = np.maximum(bboxes1_y1, bboxes2_y1)
    xx2 = np.minimum(bboxes1_x2, bboxes2_x2)
    yy2 = np.minimum(bboxes1_y2, bboxes2_y2)

    # Compute the width and height of the intersection rectangle
    inter_w = np.maximum(0.0, xx2 - xx1)
    inter_h = np.maximum(0.0, yy2 - yy1)

    # Compute the area of the intersection rectangle
    inter_area = inter_w * inter_h

    # Compute the area of both the prediction and ground-truth rectangles
    bboxes1_area = bboxes1[..., 2] * bboxes1[..., 3]
    bboxes2_area = bboxes2[..., 2] * bboxes2[..., 3]

    # Compute the intersection over union
    union_area = bboxes1_area + bboxes2_area - inter_area
    iou = inter_area / union_area

    return iou

In [52]:
def iou_batch_xywh_gpt(bboxes1, bboxes2) -> np.ndarray:
# Calculate the corners directly
    x1_1 = bboxes1[..., 0] - bboxes1[..., 2] / 2  # Top-left X1
    y1_1 = bboxes1[..., 1] - bboxes1[..., 3] / 2  # Top-left Y1
    x2_1 = bboxes1[..., 0] + bboxes1[..., 2] / 2  # Bottom-right X2
    y2_1 = bboxes1[..., 1] + bboxes1[..., 3] / 2  # Bottom-right Y2

    x1_2 = bboxes2[..., 0] - bboxes2[..., 2] / 2  # Top-left X1
    y1_2 = bboxes2[..., 1] - bboxes2[..., 3] / 2  # Top-left Y1
    x2_2 = bboxes2[..., 0] + bboxes2[..., 2] / 2  # Bottom-right X2
    y2_2 = bboxes2[..., 1] + bboxes2[..., 3] / 2  # Bottom-right Y2

    # Calculate intersection
    xx1 = np.maximum(x1_1[:, np.newaxis], x1_2[np.newaxis, :])
    yy1 = np.maximum(y1_1[:, np.newaxis], y1_2[np.newaxis, :])
    xx2 = np.minimum(x2_1[:, np.newaxis], x2_2[np.newaxis, :])
    yy2 = np.minimum(y2_1[:, np.newaxis], y2_2[np.newaxis, :])

    # Calculate width and height of the intersection
    inter_width = np.maximum(0, xx2 - xx1)
    inter_height = np.maximum(0, yy2 - yy1)
    intersection_area = inter_width * inter_height

    # Calculate areas of the bounding boxes
    area1 = (x2_1 - x1_1) * (y2_1 - y1_1)
    area2 = (x2_2 - x1_2) * (y2_2 - y1_2)

    # Calculate union
    union_area = area1[:, np.newaxis] + area2[np.newaxis, :] - intersection_area

    # Calculate IoU
    iou = intersection_area / union_area
    
    return iou

In [6]:
boxesa_xyxy = np.array([[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]])
boxesb_xyxy = np.array([[2, 3, 4, 5], [4, 5, 6, 7], [6, 7, 8, 9]])

iou_batch(boxesa_xyxy, boxesb_xyxy)

array([[0.14285714, 0.        , 0.        ],
       [0.14285714, 0.14285714, 0.        ],
       [0.        , 0.14285714, 0.14285714]])

In [38]:
boxesa_xywh = xyxy2xywh(boxesa_xyxy)
boxesb_xywh = xyxy2xywh(boxesb_xyxy)
iou_batch_xywh(boxesa_xywh, boxesb_xywh)

array([[0.14285714, 0.        , 0.        ],
       [0.14285714, 0.14285714, 0.        ],
       [0.        , 0.14285714, 0.14285714]])

In [50]:
iou_batch_xywh_gpt(boxesa_xywh, boxesb_xywh)

array([[0.14285714, 0.        , 0.        ],
       [0.14285714, 0.14285714, 0.        ],
       [0.        , 0.14285714, 0.14285714]])

In [12]:
import time

In [ ]:
from torchmetrics.functional.detection import intersection_over_union
import torch

In [28]:
iou_func = IntersectionOverUnion(box_format='xywh')

In [35]:
intersection_over_union(torch.tensor(boxesa_xywh), torch.tensor(boxesb_xywh), aggregate=False)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [53]:
n = 100000
t = time.time()
for i in range(n):
    iou_batch_xywh_gpt(boxesa_xywh, boxesb_xywh)
print(time.time() - t)
t = time.time()
for i in range(n):
    iou_batch_xywh_fastest(boxesa_xywh, boxesb_xywh)
print(time.time() - t)
t = time.time()
for i in range(n):
    iou_batch_xywh(boxesa_xywh, boxesb_xywh)
print(time.time() - t)
t = time.time()
for i in range(n):
    iou_batch(xyxy2xywh(boxesa_xyxy), xyxy2xywh(boxesb_xyxy))
print(time.time() - t)

2.052025318145752
2.009431838989258
2.4308993816375732
2.22239089012146
